Implement NGAC abstraction
ivario123/NGAC_ABE pull request #16
Opened 2022-12-08 16:21 UTC by ivario123

# Implement NGAC abstraction and a robust method of testing them
Aims to partially solve #12 and discard the remainder of it.
Aims to partially solve #4 and leave future work to be done in NGAC branch.

Moreover this PR introduces the base API that will be used in the future for the entire implementation. Thus I think that it would be beneficiall to us all if the API we end up with is as clean as possible.

## Status of pull request

- [x] Runnable ngac servers in a "platform agnostic" manner
- [x] Loading and switching between policies
- [x] Combining policies
- [x] Allowing for static attributes and validation of access requests
- [ ] Code review

## What is your solution?

### Abstraction
I wrote a NGAC class that handles the interfacing with the server leaving the end user with a clean API akin to
```python
from ngac import NGAC
from ngac_types.ngac_policy import Policy

# Create the ngac API class
ngac = NGAC()

# Create a policy, we will load from a file on disk
pol = Policy(
        name="Vehicle Ownership Policy", path="EXAMPLES/policy_vehicle_ownership.pl"
)

# Switch to the policy
unwrap(ngac.switch_to(pol,token = "admin_token"))

# Ensure the policy is loaded
print(unwrap(ngac.get(Policy,token = "admin_token")))
```

### Improvements
I removed all the python code that I had written to start the servers since that was just bloat. The frontend should not handle the backend server. So the frontend now assumes that the backend is running, allowing for cleaner and shorter code. 

## How did you test your solution?

I wrote 5 [tests](https://github.com/ivario123/NGAC_ABE/blob/ngac_boilerplate/src/NGAC/test_ngac.py) for the servers and the API.

2022-12-12 13:50 UTC, Leohemmingsson requested changes
Just found some small stuff, structure looks good!

2022-12-12 13:50 UTC, Leohemmingsson commented on src/NGAC/ngac_types/user.py
> +    <<<<<<< HEAD
More merge stuff

2022-12-13 09:59 UTC, ivario123 commented on src/NGAC/ngac.py
> +    def get(self, type: NgacType, token: str) -> requests.Response:
Fixed this. Now it only exists for policies

2022-12-13 09:59 UTC, ivario123 commented on src/NGAC/ngac_types/user.py
> +    <<<<<<< HEAD
Fixed

2022-12-13 10:00 UTC, ivario123 commented on src/NGAC/ngac.py
> +    def switch_to(self, value: NgacType, token: str = "") -> requests.Response:
Changed to 
```python
def change_policy(self, target_policy: NgacType) -> requests.Response:
```
Not quite sure change_policy is the best name though

2023-01-23 09:39 UTC, merged